version: '3.8'

services:
  ai_model_classifier:
    build:
      context: ./ai_model_classifier
      dockerfile: Dockerfile
    container_name: ai_model_classifier
    ports:
      - "8000:8000"
    volumes:
      - ./ai_model_classifier:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    command: ["python", "main.py"]
