version: '3.8'

services:
  ai_model_classifier:
    build:
      context: ./ai_model_classifier
      dockerfile: Dockerfile
    container_name: ai_model_classifier
    ports:
      - "8000:8000"
    volumes:
      - ./ai_model_classifier:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    command: ["python", "main.py"]

  tokenizer_command:
    build:
      context: ./tokenizer_command
      dockerfile: Dockerfile
    container_name: tokenizer_command
    depends_on:
      - db_command
    environment:
      - DB_HOST=db_command
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=tokenizer_command_db
    command: ["python", "main.py"]

  tokenizer_query:
    build:
      context: ./tokenizer_query
      dockerfile: Dockerfile
    container_name: tokenizer_query
    depends_on:
      - db_query
    environment:
      - DB_HOST=db_query
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=tokenizer_query_db
    command: ["python", "main.py"]

  db_command:
    image: mysql:latest
    container_name: db_command
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: tokenizer_command_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_command_data:/var/lib/mysql

  db_query:
    image: mysql:latest
    container_name: db_query
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: tokenizer_query_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - db_query_data:/var/lib/mysql

volumes:
  db_command_data:
  db_query_data: